// Category: tools/listDirectory
// Modules: 1
// Total size: 3,851 chars


// === Module: fZB (offset: 0xc9eba7, 3,851 chars) ===
var fZB=z(()=>{rC();ZE();qI();wC();xZB=dE({metadata:{name:"listDirectory",displayName:"List Directory",description:"Lists the contents of a directory, showing files and subdirectories. Returns names, types (file/directory), and file sizes. Hidden files (starting with .) are excluded by default.",category:"file"},inputSchema:S.object({path:S.string().describe("The path to the directory to list."),depth:S.number().min(1).max(JZB).optional().describe(`Optional: How deep to recurse into subdirectories. Default is 1 (immediate contents only). Maximum is ${JZB}.`)}),validateParams:()=>{return null},getDescription:({path:A})=>{return`Listing ${aJ.basename(A)||A}`},getLocations:()=>[],execute:async({path:A,depth:B=1},Q)=>{let E=Date.now(),g=aJ.isAbsolute(A)?A:aJ.resolve(Q?.workingDirectory||process.cwd(),A);fA.debug("[listDirectory] Starting",{path:g,depth:B});try{let C;try{C=await SZB(g)}catch{return fA.debug("[listDirectory] Directory not found",{path:g}),{success:!1,llmContent:`Directory not found: ${g}`,returnDisplay:"Directory not found."}}if(!C.isDirectory())return{success:!1,llmContent:`Path is not a directory: ${g}`,returnDisplay:"Path is not a directory."};let I=await fME(g,1,B),w=aJ.basename(g)||g;if(I.length===0)return{success:!0,summary:`Listed empty directory: ${w}`,llmContent:`Directory is empty: ${g}`,returnDisplay:`Empty directory: ${w}`,locations:[{path:g,type:"read"}]};let D=I.filter((G)=>G.type==="file").length,H=I.filter((G)=>G.type==="directory").length,L=I.map((G)=>{if(G.type==="directory")return`${G.name}/`;let Y=G.size!==void 0?` (${rxB(G.size)})`:"";return`${G.name}${Y}`}),R=I.length>=vKA,U=R?`

[Results truncated at ${vKA} entries]`:"";return fA.info("[listDirectory] Completed",{path:g,fileCount:D,dirCount:H,truncated:R,duration:Date.now()-E}),{success:!0,summary:`Listed ${w}: ${D} files, ${H} directories`,llmContent:`Directory: ${g}

${L.join(`
`)}${U}`,returnDisplay:`${D} files, ${H} directories`,locations:[{path:g,type:"read"}],metadata:{fileCount:D,directoryCount:H,truncated:R,toolParams:{path:A,depth:B}}}}catch(C){let I=uQ(C);return fA.error("[listDirectory] Failed",{path:g,error:I,duration:Date.now()-E}),{success:!1,llmContent:`Error listing directory: ${I}`,returnDisplay:`Error: ${I}`}}}})});import{open as cME,readdir as kME,stat as oME}from"fs/promises";import*as kD from"path";async function OME(A){try{let B=Buffer.alloc(512),Q=await cME(A,"r");try{let{bytesRead:E}=await Q.read(B,0,512,0);return B.subarray(0,E).includes(0)}finally{await Q.close()}}catch{return!1}}async function NME(A){let B=kD.extname(A).toLowerCase();if(B===".ts"||B===".tsx"||B===".js"||B===".jsx")return"text";if(B===".svg")return"svg";let Q=[".png",".jpg",".jpeg",".gif",".webp",".bmp",".tiff",".ico"],E=[".mp3",".wav",".flac",".aac",".ogg",".m4a"],g=[".mp4",".avi",".mkv",".mov",".wmv",".flv",".webm"];if(Q.includes(B))return"image";if(E.includes(B))return"audio";if(g.includes(B))return"video";if(B===".pdf")return"pdf";if([".zip",".tar",".gz",".exe",".dll",".so",".class",".jar",".war",".7z",".doc",".docx",".xls",".xlsx",".ppt",".pptx",".odt",".ods",".odp",".bin",".dat",".obj",".o",".a",".lib",".wasm",".pyc",".pyo"].includes(B))return"binary";if(await OME(A))return"binary";return"text"}function TME(A){let B=kD.extname(A).toLowerCase();return{".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".gif":"image/gif",".webp":"image/webp",".bmp":"image/bmp",".tiff":"image/tiff",".pdf":"application/pdf",".mp3":"audio/mpeg",".wav":"audio/wav",".mp4":"video/mp4",".avi":"video/x-msvideo"}[B]||"application/octet-stream"}async function yME(A){let B=kD.dirname(A),Q=kD.basename(A).toLowerCase();try{return(await kME(B)).filter((g)=>g.toLowerCase().includes(Q)||Q.includes(g.toLowerCase())).map((g)=>kD.join(B,g)).slice(0,3)}catch{return[]}}var hME=2000,cZB=2000,kZB=51200,XME=20971520,PME=1048576,oZB;
