// Category: tools/delegateSubagent
// Modules: 1
// Total size: 7,606 chars


// === Module: tVB (offset: 0xc9727f, 7,606 chars) ===
var tVB=z(()=>{rC();_VB=S.enum(["codebase-explorer","document-explorer","web-searcher","planning-agent"])});var yKA="embedder-proxy",uVB;var aVB=z(async()=>{xFA();fFA();kFA();R9();rC();oF();fw();ZE();qI();wC();tVB();await gz();uVB=dE({metadata:{name:"delegateSubagent",displayName:"Delegate to Subagent",description:`Launch a new agent to handle multi-step tasks autonomously.

The delegateSubagent tool launches specialized agents (subprocesses) that autonomously handle complex tasks. Each agent type has specific capabilities and tools available to it.

Available subagent types:
- codebase-explorer: Navigate codebase, find files, analyze structure (READ-ONLY)
- document-explorer: Search hardware documentation, synthesize datasheet information (READ-ONLY)
- web-searcher: Search the web for information using web context tool (READ-ONLY)
- planning-agent: Analyze codebase and create detailed implementation plans (READ-ONLY)

Each subagent has an isolated context window and specialized system prompt.
Use when a task requires deep exploration or analysis without polluting main context.

When NOT to use this tool:
- If you want to read a specific file path, use the readFile or glob tool instead of the delegateSubagent tool, to find the match more quickly
- If you are searching for a specific class definition like "class Foo", use the glob tool instead, to find the match more quickly
- If you are searching for code within a specific file, use the readFile tool instead of the delegateSubagent tool, to find the match more quickly
- Other tasks that are not related to the agent descriptions above

The subagent will use tools to complete the task and return a summarized report.`,category:"system",isOutputMarkdown:!0,canStream:!0,requiresConfirmation:!1},inputSchema:S.object({agent_type:_VB.describe("The type of specialized subagent to use (codebase-explorer, document-explorer, web-searcher, planning-agent)"),task_description:S.string().min(10).max(1000).describe("Clear description of what the subagent should accomplish (10-1000 chars)"),context:S.string().optional().describe("Optional additional context for the subagent (file paths, constraints, etc.)")}),validateParams:({task_description:A})=>{if(!A?.trim())return"Task description cannot be empty";if(A.trim().split(/\s+/).length<5)return"Task description should be more detailed (at least 5 words)";return null},getDescription:({agent_type:A,task_description:B})=>{let Q=B.length>60?`${B.substring(0,60)}...`:B;return`Delegating to ${A}: ${Q}`},getDisplayName:({agent_type:A})=>{switch(A){case"codebase-explorer":return"Exploring Codebase";case"document-explorer":return"Exploring Documentation";case"planning-agent":return"Creating Plan";case"web-searcher":return"Searching the Web";default:return"Delegate to Subagent"}},getLocations:()=>[],execute:async(A,B)=>{if(!B.getAiHeaders)return{success:!1,llmContent:"AI headers provider not available.",returnDisplay:"Configuration error",summary:"Configuration error"};if(!B.aiRegistry)return{success:!1,llmContent:"AI registry not available in context.",returnDisplay:"Configuration error",summary:"Configuration error"};try{let Q=await B.getAiHeaders(),E=await fetch(`${OC.apiUrl}/api/v1/subagents/${A.agent_type}/config`,{method:"GET",headers:{...Q,"Content-Type":"application/json"}});if(!E.ok)throw Error(`Failed to load subagent config: ${E.status}`);let g=await E.json(),C=await VKA(g.allowedTools),I=[`Task: ${A.task_description}`,A.context&&`Additional Context: ${A.context}`,`Working Directory: ${B.workingDirectory}`,`Project Root: ${B.projectRoot}`].filter(Boolean).join(`

`),w={...Q,"x-agent-mode":`subagent-${A.agent_type}`},D=async(T,k)=>{let q=new Headers(k?.headers);for(let[s,j]of Object.entries(w))q.set(s,j);return fetch(T,{...k,headers:q})},H;switch(g.provider){case"anthropic":H=C9({baseURL:`${OC.apiUrl}/api/v1/proxy/anthropic/`,apiKey:yKA,fetch:D});break;case"openai":H=D9({baseURL:`${OC.apiUrl}/api/v1/proxy/openai/`,apiKey:yKA,fetch:D});break;case"google":H=w9({baseURL:`${OC.apiUrl}/api/v1/proxy/google/`,apiKey:yKA,fetch:D});break;default:throw Error(`Unsupported provider: ${g.provider}`)}let L=H(g.modelId),R=g.timeoutMinutes*60*1000,U=new AbortController,G=setTimeout(()=>U.abort(),R),Y=yB.getState().autoApprovalHandler;Y?.(!0);let J="",c=[];try{let T=await G4({model:L,messages:[{role:"user",content:I}],tools:C,maxOutputTokens:g.maxTokens,stopWhen:G9(g.maxToolCalls),abortSignal:U.signal,temperature:g.temperature});fA.info("Subagent stream starting",{agentType:A.agent_type,toolsAvailable:Object.keys(C).length});let k=yB.getState().nestedToolCallHandler,q=yB.getState().nestedToolUpdateHandler,s=B.toolCallId;for await(let j of T.fullStream)switch(fA.debug("Subagent chunk received",{type:j.type,agentType:A.agent_type}),j.type){case"text-delta":J+=j.text;break;case"tool-call":{if(!c.includes(j.toolName))c.push(j.toolName);fA.info("Subagent tool call",{agentType:A.agent_type,toolName:j.toolName});let i=uJ[j.toolName],d={toolCallId:j.toolCallId,toolName:j.toolName,displayName:i?.metadata?.displayName||j.toolName,status:"executing",args:"input"in j?j.input:{},startTime:Date.now()};if(s&&k)k(s,d);break}case"tool-result":{let i=j.toolCallId;if(s&&q){let d=typeof j.output==="object"&&j.output!==null?j.output.success:!0,l=typeof j.output==="object"&&j.output!==null?j.output.summary||"Completed":"Completed";q(s,i,{status:d?"success":"error",result:{success:d,summary:l},endTime:Date.now()}),fA.debug("Subagent tool result",{agentType:A.agent_type,toolName:j.toolName,success:d})}break}case"tool-error":if(fA.error("Subagent tool error",{agentType:A.agent_type,toolName:j.toolName,error:j.error}),s&&q){let i=j,d=i.error instanceof Error?i.error.message:String(i.error);q(s,i.toolCallId,{status:"error",result:{success:!1,summary:d},endTime:Date.now()})}break;case"error":fA.error("Subagent stream error",{agentType:A.agent_type,error:j.error});break;case"finish":fA.info("Subagent stream finished",{agentType:A.agent_type,finishReason:j.finishReason,textLength:J.length,toolsUsed:c.length});break}fA.info("Subagent execution complete",{agentType:A.agent_type,accumulatedTextLength:J.length,toolsUsed:c})}finally{clearTimeout(G),Y?.(!1)}let V=J.match(/^##?\s*Summary\s*\n+(.+?)(?:\n\n|$)/is)?.[1]?.trim()||`${J.substring(0,200).trim()}...`;if(!J)return{success:!1,llmContent:"Subagent completed but returned no results",returnDisplay:"No results returned",summary:"No results"};return{success:!0,llmContent:`## ${A.agent_type} Result

${J}`,returnDisplay:`\u2713 ${A.agent_type}: ${V}`,summary:V,metadata:{agent_type:A.agent_type,tools_used:c,output_length:J.length,task_description:A.task_description}}}catch(Q){let E=uQ(Q);return{success:!1,llmContent:`Subagent delegation failed: ${E}`,returnDisplay:`Error: ${E}`,summary:"Delegation failed",metadata:{agent_type:A.agent_type,error_message:E}}}}})});var EME,lVB;var $VB=z(()=>{rC();EME=S.object({label:S.string().min(1).max(50).describe("Display text for this option"),description:S.string().min(1).describe("Explanation of what this option means")}),lVB=S.object({question:S.string().min(1).describe("The question to ask (should end with '?')"),header:S.string().min(1).max(30).describe("Short label/tag for the question (max 30 chars)"),options:S.array(EME).min(1).max(4).describe("Available choices (1-4 options)"),multiSelect:S.boolean().describe("If true, shows checkboxes and allows multiple selections. If false, shows radio buttons for single selection only.")})});function mVB(A){yB.getState().setQuestionHandler(A)}function nVB(){yB.getState().setQuestionHandler(null)}var pVB;
