import { z } from "zod";

/**
 * Expected structure of an EMBEDDER.md file generated by scenario 03.
 */
export const EmbedderMdSchema = z.object({
  overview: z.object({
    name: z.string().min(1),
    targetMcu: z.string().regex(/stm32g4/i),
    board: z.string().optional(),
    toolchain: z.string().regex(/arm-none-eabi/i),
    debugInterface: z.string().regex(/st-?link/i),
    projectSummary: z.string().optional(),
  }),
  commands: z.object({
    buildCommand: z.string().min(1),
    flashCommand: z.string().regex(/openocd/i),
    serialPort: z.string().regex(/\/dev\/ttyACM/i),
    serialBaudrate: z.number().or(z.string()).transform(String),
  }),
});

/**
 * Parse EMBEDDER.md content into a structured object for validation.
 */
export function parseEmbedderMd(content: string): Record<string, any> {
  const result: Record<string, any> = {
    overview: {} as Record<string, string>,
    commands: {} as Record<string, string | number>,
  };

  const lines = content.split("\n");
  let currentSection = "";

  for (const line of lines) {
    if (line.includes("<OVERVIEW>")) {
      currentSection = "overview";
      continue;
    }
    if (line.includes("</OVERVIEW>")) {
      currentSection = "";
      continue;
    }
    if (line.includes("<COMMANDS>")) {
      currentSection = "commands";
      continue;
    }
    if (line.includes("</COMMANDS>")) {
      currentSection = "";
      continue;
    }

    const kvMatch = line.match(/^\s*([A-Za-z_][A-Za-z0-9_ ]*?)\s*=\s*(.+)$/);
    if (kvMatch && currentSection) {
      const key = kvMatch[1].trim().replace(/\s+/g, "_").toLowerCase();
      const value = kvMatch[2].trim();
      (result[currentSection] as Record<string, string>)[key] = value;
    }
  }

  return result;
}

/**
 * Expected Makefile structure for scenario 08.
 */
export const MakefileSchema = z.object({
  hasAllTarget: z.boolean(),
  hasFlashTarget: z.boolean(),
  hasCleanTarget: z.boolean(),
  compiler: z.string().regex(/arm-none-eabi-gcc/),
  cpuFlag: z.string().regex(/-mcpu=cortex-m4/),
  fpuFlag: z.string().regex(/-mfpu=fpv4-sp-d16/),
  flashOrigin: z.string().regex(/0x08000000/i),
});

/**
 * Expected main.c structure for scenario 07.
 */
export const MainCSchema = z.object({
  hasRccEnable: z.boolean(),
  hasGpioConfig: z.boolean(),
  hasToggleLogic: z.boolean(),
  hasMainLoop: z.boolean(),
  includes: z.array(z.string()),
  functions: z.array(z.string()),
});
